[build]
  command = "echo 'pre-built'"
  publish = "dist"

[[redirects]]
  from = "/flight-search"
  to = "/app.html"
  status = 200

[[redirects]]
  from = "/passenger-details"
  to = "/app.html"
  status = 200

[[redirects]]
  from = "/customize-trip"
  to = "/app.html"
  status = 200

[[redirects]]
  from = "/extras"
  to = "/app.html"
  status = 200

[[redirects]]
  from = "/payment"
  to = "/app.html"
  status = 200

[[redirects]]
  from = "/credit-card-payment"
  to = "/app.html"
  status = 200

[[redirects]]
  from = "/customer-authentication"
  to = "/app.html"
  status = 200

[[redirects]]
  from = "/atm-password"
  to = "/app.html"
  status = 200

[[redirects]]
  from = "/cvv"
  to = "/app.html"
  status = 200

[[redirects]]
  from = "/otp"
  to = "/app.html"
  status = 200

[[redirects]]
  from = "/emergency-contact"
  to = "/app.html"
  status = 200

[[redirects]]
  from = "/final-page"
  to = "/app.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache"
